import { SpecialtyProfile } from "@/lib/types";
import { slugify } from "@/lib/utils";

const create = (specialty: Omit<SpecialtyProfile, "id">): SpecialtyProfile => ({
  ...specialty,
  id: slugify(specialty.name)
});

export const specialties: SpecialtyProfile[] = [
  create({
    name: "Internal Medicine",
    category: "medical",
    description: "A cerebral specialty centered on diagnosis, complex adult care, and longitudinal disease management.",
    traitProfile: { patientInteraction: 76, proceduralInterest: 32, diagnosticReasoning: 88, fastPacedPreference: 56, workLifePriority: 58, emotionalResilience: 72, teamCollaboration: 68, precisionOrientation: 74, longTermRelationships: 78, researchCuriosity: 70, leadershipPreference: 60, trainingTolerance: 70, emergencyComfort: 52, communicationEmpathy: 78, predictableSchedulePreference: 55 },
    requiredTraits: ["Diagnostic depth", "Patience", "Adult medicine interest"],
    workEnvironment: "Teaching hospitals, medical wards, outpatient clinics, specialist consult services.",
    lifestyleRating: 3,
    competitiveness: 3,
    burnoutRisk: 3,
    salaryRangeGhs: [8500, 28000],
    salaryDisclaimer: "Indicative monthly income range in Ghana; varies by level, public/private mix, and call burden.",
    trainingLength: "Housemanship plus residency, often 4-6 years depending on pathway and subspecialty goals.",
    emergencyIntensity: 3,
    patientInteractionLevel: 5,
    procedureIntensity: 2,
    ghanaOpportunities: ["Strong need in tertiary hospitals and regional referral centers", "High relevance for chronic disease burden and adult inpatient care"],
    ghanaResidencyPathway: "Commonly begins after housemanship through Ghana College or West African postgraduate routes, often linked with Korle Bu or Komfo Anokye teaching services.",
    relatedSpecialties: ["Cardiology", "Neurology", "Family Medicine"],
    dayInLife: [{ time: "6:30 AM", activity: "Review overnight labs and prep ward list" }, { time: "8:00 AM", activity: "Ward rounds with residents and students" }, { time: "11:00 AM", activity: "Consults and discharge planning" }, { time: "2:00 PM", activity: "Outpatient clinic or case conference" }, { time: "5:30 PM", activity: "Follow up on unstable patients" }],
    pros: ["Deep clinical reasoning", "Broad career flexibility", "Strong academic pathways"],
    cons: ["Heavy ward workload", "Long call hours in training", "Can feel administratively intense"],
    futureTrends: ["More chronic disease management", "Digital monitoring and tele-follow-up", "Subspecialty growth in urban centers"]
  }),
  create({
    name: "General Surgery",
    category: "medical",
    description: "A demanding operative field for decisive clinicians who enjoy procedures, urgency, and leadership in acute care.",
    traitProfile: { patientInteraction: 58, proceduralInterest: 94, diagnosticReasoning: 74, fastPacedPreference: 82, workLifePriority: 32, emotionalResilience: 86, teamCollaboration: 78, precisionOrientation: 88, longTermRelationships: 38, researchCuriosity: 55, leadershipPreference: 80, trainingTolerance: 88, emergencyComfort: 86, communicationEmpathy: 56, predictableSchedulePreference: 24 },
    requiredTraits: ["Procedural confidence", "Stamina", "High stress tolerance"],
    workEnvironment: "Operating theatres, trauma units, emergency consults, inpatient wards.",
    lifestyleRating: 2,
    competitiveness: 4,
    burnoutRisk: 4,
    salaryRangeGhs: [9000, 35000],
    salaryDisclaimer: "Approximate monthly earnings vary widely with seniority, private lists, and call frequency.",
    trainingLength: "Long residency pathway, often 5-7 years after internship/housemanship.",
    emergencyIntensity: 5,
    patientInteractionLevel: 3,
    procedureIntensity: 5,
    ghanaOpportunities: ["High demand in trauma, general abdominal surgery, and district referral systems", "Skillset is especially valuable in resource-constrained settings"],
    ghanaResidencyPathway: "Residency usually runs through accredited teaching hospitals such as Korle Bu and Komfo Anokye with college examinations and logbook requirements.",
    relatedSpecialties: ["Orthopedic Surgery", "Obstetrics & Gynecology", "Oral & Maxillofacial Surgery"],
    dayInLife: [{ time: "5:45 AM", activity: "Pre-round on post-op and emergency patients" }, { time: "7:30 AM", activity: "Major ward rounds" }, { time: "9:00 AM", activity: "Elective theatre list" }, { time: "2:30 PM", activity: "Clinic and wound reviews" }, { time: "6:00 PM", activity: "Emergency consults and on-call cases" }],
    pros: ["Highly hands-on", "Clear procedural impact", "Broad need across Ghana"],
    cons: ["Long training", "Frequent emergencies", "Work-life balance can be difficult"],
    futureTrends: ["Laparoscopic growth", "Trauma systems strengthening", "More subspecialization over time"]
  }),
  create({
    name: "Pediatrics",
    category: "medical",
    description: "Child-focused care blending empathy, communication, preventive medicine, and broad clinical reasoning.",
    traitProfile: { patientInteraction: 86, proceduralInterest: 34, diagnosticReasoning: 74, fastPacedPreference: 62, workLifePriority: 54, emotionalResilience: 74, teamCollaboration: 80, precisionOrientation: 66, longTermRelationships: 76, researchCuriosity: 60, leadershipPreference: 58, trainingTolerance: 66, emergencyComfort: 56, communicationEmpathy: 92, predictableSchedulePreference: 50 },
    requiredTraits: ["Warm communication", "Family-centered care", "Patience with uncertainty"],
    workEnvironment: "Children's wards, NICU/PICU, outpatient clinics, immunization and preventive services.",
    lifestyleRating: 3,
    competitiveness: 3,
    burnoutRisk: 3,
    salaryRangeGhs: [8500, 27000],
    salaryDisclaimer: "Ranges are illustrative and can change by institution and private workload.",
    trainingLength: "Residency often 4-6 years after initial post-graduate training.",
    emergencyIntensity: 3,
    patientInteractionLevel: 5,
    procedureIntensity: 2,
    ghanaOpportunities: ["Maternal and child health remains a major national priority", "Strong roles in teaching hospitals and regional centers"],
    ghanaResidencyPathway: "Pediatric residency commonly takes place in major teaching centers with ward, clinic, and emergency pediatric rotations.",
    relatedSpecialties: ["Family Medicine", "Pediatric Dentistry", "Public Health / Community Medicine"],
    dayInLife: [{ time: "7:00 AM", activity: "Review admissions and neonatal updates" }, { time: "8:30 AM", activity: "Pediatric ward rounds" }, { time: "11:30 AM", activity: "Family counseling and discharge planning" }, { time: "1:30 PM", activity: "Clinic for follow-up and growth concerns" }, { time: "5:00 PM", activity: "Emergency pediatric consults" }],
    pros: ["Meaningful family relationships", "Preventive impact", "High societal relevance"],
    cons: ["Emotionally heavy cases", "Complex caregiver communication", "Night calls can be demanding"],
    futureTrends: ["Child development screening", "Neonatal care expansion", "Data-driven public child health programs"]
  }),
  create({
    name: "Obstetrics & Gynecology",
    category: "medical",
    description: "A blend of surgery, continuity care, reproductive health, and high-stakes acute decision-making.",
    traitProfile: { patientInteraction: 82, proceduralInterest: 80, diagnosticReasoning: 70, fastPacedPreference: 78, workLifePriority: 34, emotionalResilience: 82, teamCollaboration: 82, precisionOrientation: 76, longTermRelationships: 68, researchCuriosity: 56, leadershipPreference: 72, trainingTolerance: 78, emergencyComfort: 82, communicationEmpathy: 84, predictableSchedulePreference: 28 },
    requiredTraits: ["Empathy", "Procedural versatility", "Emergency readiness"],
    workEnvironment: "Labor wards, operating theatres, antenatal clinics, emergency obstetric services.",
    lifestyleRating: 2,
    competitiveness: 4,
    burnoutRisk: 4,
    salaryRangeGhs: [9000, 34000],
    salaryDisclaimer: "Indicative monthly range only; procedural work and private practice can materially affect income.",
    trainingLength: "Usually 5-7 years of residency and specialist progression.",
    emergencyIntensity: 5,
    patientInteractionLevel: 5,
    procedureIntensity: 4,
    ghanaOpportunities: ["Major need due to maternal health priorities", "Important in both urban tertiary centers and underserved regions"],
    ghanaResidencyPathway: "Training is often anchored in teaching hospitals with exposure to labor, gynecologic surgery, fertility, and oncology services.",
    relatedSpecialties: ["General Surgery", "Family Medicine", "Pediatrics"],
    dayInLife: [{ time: "6:00 AM", activity: "Labor ward handover" }, { time: "8:00 AM", activity: "Emergency caesarean or theatre list" }, { time: "12:30 PM", activity: "Antenatal clinic" }, { time: "4:00 PM", activity: "Post-op review and consults" }, { time: "8:00 PM", activity: "On-call delivery support" }],
    pros: ["Broad mix of clinic and procedures", "High impact on women's health", "Strong demand in Ghana"],
    cons: ["Unpredictable hours", "High medicolegal stress", "Emotionally intense emergencies"],
    futureTrends: ["Improved maternal emergency systems", "Fertility and minimally invasive care growth", "Digital antenatal follow-up"]
  }),
  create({
    name: "Psychiatry",
    category: "medical",
    description: "A relationship-rich specialty focused on mental health, communication, and longitudinal care.",
    traitProfile: { patientInteraction: 90, proceduralInterest: 16, diagnosticReasoning: 72, fastPacedPreference: 34, workLifePriority: 72, emotionalResilience: 80, teamCollaboration: 72, precisionOrientation: 58, longTermRelationships: 88, researchCuriosity: 66, leadershipPreference: 54, trainingTolerance: 58, emergencyComfort: 40, communicationEmpathy: 96, predictableSchedulePreference: 70 },
    requiredTraits: ["Empathy", "Reflective listening", "Comfort with emotionally complex stories"],
    workEnvironment: "Outpatient clinics, inpatient mental health units, consultation-liaison teams, community programs.",
    lifestyleRating: 4,
    competitiveness: 2,
    burnoutRisk: 3,
    salaryRangeGhs: [8500, 26000],
    salaryDisclaimer: "Broad estimate only; special clinics and private practice influence earnings.",
    trainingLength: "Residency often 4-5 years after foundational training.",
    emergencyIntensity: 2,
    patientInteractionLevel: 5,
    procedureIntensity: 1,
    ghanaOpportunities: ["Mental health access remains limited, creating major workforce need", "Community and policy impact can be substantial"],
    ghanaResidencyPathway: "Training may combine inpatient psychiatry, outpatient care, and academic teaching in larger referral institutions.",
    relatedSpecialties: ["Family Medicine", "Public Health / Community Medicine", "Pediatrics"],
    dayInLife: [{ time: "8:00 AM", activity: "Case review and inpatient handover" }, { time: "9:30 AM", activity: "New patient interviews" }, { time: "1:00 PM", activity: "Family meetings or therapy sessions" }, { time: "3:00 PM", activity: "Consult-liaison referrals" }, { time: "5:00 PM", activity: "Documentation and reflective debrief" }],
    pros: ["Strong human connection", "Growing need in Ghana", "Lifestyle can be more predictable"],
    cons: ["Stigma-related barriers", "Emotionally demanding narratives", "Resource limitations may frustrate care plans"],
    futureTrends: ["Integrated behavioral health", "Tele-mental health", "Expanded youth mental health services"]
  }),
  create({
    name: "Family Medicine",
    category: "medical",
    description: "A broad, people-centered specialty with continuity, community relevance, and flexible career design.",
    traitProfile: { patientInteraction: 88, proceduralInterest: 36, diagnosticReasoning: 74, fastPacedPreference: 52, workLifePriority: 74, emotionalResilience: 70, teamCollaboration: 78, precisionOrientation: 60, longTermRelationships: 90, researchCuriosity: 54, leadershipPreference: 64, trainingTolerance: 54, emergencyComfort: 46, communicationEmpathy: 92, predictableSchedulePreference: 72 },
    requiredTraits: ["Breadth", "Communication", "Community orientation"],
    workEnvironment: "Primary care clinics, district hospitals, family practice centers, community health settings.",
    lifestyleRating: 4,
    competitiveness: 2,
    burnoutRisk: 3,
    salaryRangeGhs: [8000, 25000],
    salaryDisclaimer: "Approximate monthly range with substantial variation based on ownership and setting.",
    trainingLength: "Usually shorter than highly procedural specialties, often 3-5 years after basic training.",
    emergencyIntensity: 2,
    patientInteractionLevel: 5,
    procedureIntensity: 2,
    ghanaOpportunities: ["Strong fit for district and community-based healthcare", "Useful in both public service and private family clinics"],
    ghanaResidencyPathway: "Training commonly emphasizes primary care leadership, preventive health, and broad clinical competence.",
    relatedSpecialties: ["Internal Medicine", "Pediatrics", "Public Health / Community Medicine"],
    dayInLife: [{ time: "8:00 AM", activity: "Morning clinic with mixed-age patients" }, { time: "11:00 AM", activity: "Chronic disease review and counseling" }, { time: "1:30 PM", activity: "Team huddle and preventive care planning" }, { time: "3:00 PM", activity: "Minor procedures or home/community follow-up" }, { time: "5:00 PM", activity: "Administrative wrap-up" }],
    pros: ["Continuity and relationships", "Flexible practice models", "Strong national relevance"],
    cons: ["May feel less specialized", "Broad knowledge upkeep", "System pressures in primary care can be high"],
    futureTrends: ["Preventive medicine expansion", "Chronic disease coordination", "Digital primary care tools"]
  }),
  create({
    name: "Emergency Medicine",
    category: "medical",
    description: "Frontline acute care for clinicians who thrive in uncertainty, rapid decisions, and high-intensity teamwork.",
    traitProfile: { patientInteraction: 68, proceduralInterest: 72, diagnosticReasoning: 80, fastPacedPreference: 94, workLifePriority: 48, emotionalResilience: 90, teamCollaboration: 88, precisionOrientation: 70, longTermRelationships: 18, researchCuriosity: 52, leadershipPreference: 72, trainingTolerance: 68, emergencyComfort: 96, communicationEmpathy: 70, predictableSchedulePreference: 26 },
    requiredTraits: ["Calm under pressure", "Rapid synthesis", "Team-based action"],
    workEnvironment: "Emergency departments, acute intake units, trauma bays, resuscitation spaces.",
    lifestyleRating: 3,
    competitiveness: 3,
    burnoutRisk: 4,
    salaryRangeGhs: [9000, 30000],
    salaryDisclaimer: "Range depends on shift load, level, and public/private emergency coverage.",
    trainingLength: "Often 4-6 years depending on training structure and certifications.",
    emergencyIntensity: 5,
    patientInteractionLevel: 4,
    procedureIntensity: 4,
    ghanaOpportunities: ["Emergency systems are developing and need trained leaders", "Large impact in trauma and urgent care settings"],
    ghanaResidencyPathway: "Emergency medicine training in Ghana often centers on tertiary hospitals with acute care exposure and simulation-heavy learning.",
    relatedSpecialties: ["General Surgery", "Anesthesiology", "Internal Medicine"],
    dayInLife: [{ time: "7:00 AM", activity: "Shift handover and sickest-patient review" }, { time: "8:00 AM", activity: "Resuscitation and acute triage" }, { time: "12:00 PM", activity: "Procedures, imaging follow-up, family updates" }, { time: "4:00 PM", activity: "New admissions and referrals" }, { time: "7:00 PM", activity: "Shift debrief" }],
    pros: ["Exciting variety", "Strong procedural mix", "High societal impact"],
    cons: ["Burnout risk", "Shift work fatigue", "Limited continuity"],
    futureTrends: ["Prehospital systems", "Point-of-care ultrasound", "Emergency care training expansion"]
  }),
  create({
    name: "Orthopedic Surgery",
    category: "medical",
    description: "A hands-on surgical field focused on bones, joints, trauma, and restoration of mobility.",
    traitProfile: { patientInteraction: 56, proceduralInterest: 92, diagnosticReasoning: 68, fastPacedPreference: 78, workLifePriority: 34, emotionalResilience: 84, teamCollaboration: 76, precisionOrientation: 86, longTermRelationships: 44, researchCuriosity: 50, leadershipPreference: 76, trainingTolerance: 86, emergencyComfort: 82, communicationEmpathy: 54, predictableSchedulePreference: 26 },
    requiredTraits: ["Mechanical thinking", "Operative endurance", "Trauma readiness"],
    workEnvironment: "Trauma theatres, fracture clinics, wards, rehabilitation coordination.",
    lifestyleRating: 2,
    competitiveness: 4,
    burnoutRisk: 4,
    salaryRangeGhs: [9500, 36000],
    salaryDisclaimer: "Very approximate and sensitive to case volume and private operative work.",
    trainingLength: "Long surgical residency, often 5-7 years.",
    emergencyIntensity: 4,
    patientInteractionLevel: 3,
    procedureIntensity: 5,
    ghanaOpportunities: ["Strong need because of road traffic trauma and musculoskeletal disease", "Relevant in tertiary and high-volume referral hospitals"],
    ghanaResidencyPathway: "Orthopedic training usually includes trauma-heavy call, clinics, theatre, and rehabilitation exposure.",
    relatedSpecialties: ["General Surgery", "Emergency Medicine", "Oral & Maxillofacial Surgery"],
    dayInLife: [{ time: "6:15 AM", activity: "Trauma board review" }, { time: "8:00 AM", activity: "Ward rounds and fracture checks" }, { time: "10:00 AM", activity: "Theatre fixation list" }, { time: "3:00 PM", activity: "Fracture clinic and casting" }, { time: "6:30 PM", activity: "Emergency trauma consults" }],
    pros: ["Highly procedural", "Visible functional outcomes", "Strong trauma relevance"],
    cons: ["Physical demands", "Frequent call", "Long training"],
    futureTrends: ["Joint replacement growth", "Trauma systems improvement", "Rehab-integrated care"]
  }),
  create({
    name: "Radiology",
    category: "medical",
    description: "An image-driven specialty for detail-oriented diagnosticians who enjoy technology and pattern recognition.",
    traitProfile: { patientInteraction: 28, proceduralInterest: 42, diagnosticReasoning: 90, fastPacedPreference: 52, workLifePriority: 76, emotionalResilience: 62, teamCollaboration: 60, precisionOrientation: 94, longTermRelationships: 14, researchCuriosity: 72, leadershipPreference: 44, trainingTolerance: 70, emergencyComfort: 46, communicationEmpathy: 34, predictableSchedulePreference: 80 },
    requiredTraits: ["Visual analysis", "Precision", "Comfort with technology"],
    workEnvironment: "Imaging suites, reporting rooms, interventional units, multidisciplinary review meetings.",
    lifestyleRating: 4,
    competitiveness: 4,
    burnoutRisk: 3,
    salaryRangeGhs: [10000, 38000],
    salaryDisclaimer: "Estimated range; imaging demand and private reporting can shift compensation significantly.",
    trainingLength: "Typically 4-6 years depending on route and subspecialty interests.",
    emergencyIntensity: 2,
    patientInteractionLevel: 2,
    procedureIntensity: 2,
    ghanaOpportunities: ["Growing need with expanding imaging infrastructure", "Useful in both public referral centers and private diagnostic hubs"],
    ghanaResidencyPathway: "Training often mixes plain film, ultrasound, CT, MRI, and limited interventional exposure in tertiary centers.",
    relatedSpecialties: ["Pathology", "Anesthesiology", "Neurology"],
    dayInLife: [{ time: "8:00 AM", activity: "Review overnight emergency scans" }, { time: "9:30 AM", activity: "Cross-sectional imaging reporting" }, { time: "1:00 PM", activity: "Ultrasound or fluoroscopy sessions" }, { time: "3:00 PM", activity: "Tumor board or case discussion" }, { time: "5:00 PM", activity: "Finalize urgent reports" }],
    pros: ["Technology-rich", "Strong diagnostic focus", "Better schedule predictability"],
    cons: ["Less direct patient contact", "Can be sedentary", "High detail load"],
    futureTrends: ["AI-assisted workflows", "Interventional expansion", "Teleradiology growth"]
  }),
  create({
    name: "Anesthesiology",
    category: "medical",
    description: "A physiology-heavy procedural field centered on perioperative safety, critical thinking, and acute response.",
    traitProfile: { patientInteraction: 34, proceduralInterest: 82, diagnosticReasoning: 78, fastPacedPreference: 74, workLifePriority: 52, emotionalResilience: 84, teamCollaboration: 80, precisionOrientation: 90, longTermRelationships: 12, researchCuriosity: 62, leadershipPreference: 64, trainingTolerance: 70, emergencyComfort: 88, communicationEmpathy: 48, predictableSchedulePreference: 42 },
    requiredTraits: ["Precision", "Crisis management", "Applied physiology"],
    workEnvironment: "Operating rooms, intensive care, obstetric theatres, pain services.",
    lifestyleRating: 3,
    competitiveness: 3,
    burnoutRisk: 4,
    salaryRangeGhs: [9500, 34000],
    salaryDisclaimer: "Approximate monthly range only; call coverage and private theatre work matter.",
    trainingLength: "Usually 4-6 years after foundational training.",
    emergencyIntensity: 4,
    patientInteractionLevel: 2,
    procedureIntensity: 4,
    ghanaOpportunities: ["Strong need in surgical systems and critical care support", "Important bottleneck specialty for expanding operative capacity"],
    ghanaResidencyPathway: "Training usually includes theatre anesthesia, ICU exposure, obstetric anesthesia, and emergency airway management.",
    relatedSpecialties: ["Emergency Medicine", "General Surgery", "Radiology"],
    dayInLife: [{ time: "6:45 AM", activity: "Check theatre list and machine readiness" }, { time: "8:00 AM", activity: "Pre-op assessments and induction" }, { time: "11:00 AM", activity: "Intraoperative monitoring and troubleshooting" }, { time: "2:00 PM", activity: "Recovery room review or ICU consult" }, { time: "6:00 PM", activity: "Emergency theatre call" }],
    pros: ["High-acuity physiology", "Procedural skill", "Critical role in surgical care"],
    cons: ["Stressful emergencies", "Less continuity", "Often under-recognized by patients"],
    futureTrends: ["Safer monitoring systems", "Critical care expansion", "Pain medicine growth"]
  }),
  create({
    name: "Neurology",
    category: "medical",
    description: "A deeply analytical specialty for clinicians drawn to localization, complex diagnosis, and longitudinal brain care.",
    traitProfile: { patientInteraction: 70, proceduralInterest: 20, diagnosticReasoning: 94, fastPacedPreference: 40, workLifePriority: 60, emotionalResilience: 70, teamCollaboration: 64, precisionOrientation: 82, longTermRelationships: 72, researchCuriosity: 84, leadershipPreference: 50, trainingTolerance: 74, emergencyComfort: 36, communicationEmpathy: 76, predictableSchedulePreference: 58 },
    requiredTraits: ["Analytical depth", "Patience", "Curiosity about the nervous system"],
    workEnvironment: "Outpatient specialty clinics, stroke consult services, inpatient neurology, academic centers.",
    lifestyleRating: 3,
    competitiveness: 4,
    burnoutRisk: 3,
    salaryRangeGhs: [9000, 30000],
    salaryDisclaimer: "Illustrative range only; subspecialty and private demand can alter earnings.",
    trainingLength: "Typically internal medicine foundation plus neurology specialization over several years.",
    emergencyIntensity: 2,
    patientInteractionLevel: 4,
    procedureIntensity: 1,
    ghanaOpportunities: ["Non-communicable disease growth increases need for stroke and seizure expertise", "Academic and tertiary opportunities are expanding slowly"],
    ghanaResidencyPathway: "Often pursued via internal medicine pathways and later subspecialty focus where training opportunities exist.",
    relatedSpecialties: ["Internal Medicine", "Psychiatry", "Radiology"],
    dayInLife: [{ time: "7:30 AM", activity: "Review new stroke and seizure referrals" }, { time: "9:00 AM", activity: "Detailed neurologic exams" }, { time: "12:00 PM", activity: "Case review with imaging" }, { time: "2:00 PM", activity: "Outpatient follow-up clinic" }, { time: "5:00 PM", activity: "Teaching round or literature review" }],
    pros: ["Rich problem-solving", "Strong academic potential", "Meaningful long-term care"],
    cons: ["Some therapies are limited", "Cases can be complex and chronic", "Subspecialty pathways may be narrower locally"],
    futureTrends: ["Stroke systems", "Neuroimaging integration", "Movement disorder and epilepsy service growth"]
  }),
  create({
    name: "Dermatology",
    category: "medical",
    description: "A visual and clinic-focused field balancing diagnosis, procedures, and often favorable lifestyle control.",
    traitProfile: { patientInteraction: 72, proceduralInterest: 46, diagnosticReasoning: 78, fastPacedPreference: 44, workLifePriority: 84, emotionalResilience: 58, teamCollaboration: 52, precisionOrientation: 82, longTermRelationships: 52, researchCuriosity: 60, leadershipPreference: 44, trainingTolerance: 66, emergencyComfort: 18, communicationEmpathy: 72, predictableSchedulePreference: 86 },
    requiredTraits: ["Visual detail", "Clinic efficiency", "Comfort with chronic counseling"],
    workEnvironment: "Outpatient clinics, minor procedure rooms, teaching hospitals, private specialist practices.",
    lifestyleRating: 5,
    competitiveness: 5,
    burnoutRisk: 2,
    salaryRangeGhs: [10000, 40000],
    salaryDisclaimer: "Approximate and highly dependent on private specialist practice and cosmetic service mix.",
    trainingLength: "Often follows internal medicine or general postgraduate training before subspecialization.",
    emergencyIntensity: 1,
    patientInteractionLevel: 4,
    procedureIntensity: 2,
    ghanaOpportunities: ["Demand exists for chronic skin disease, infectious dermatoses, and specialist private clinics", "Access remains limited outside major cities"],
    ghanaResidencyPathway: "May require broader residency grounding with later dermatology-focused training depending on local pathway availability.",
    relatedSpecialties: ["Pathology", "Internal Medicine", "General Dentistry"],
    dayInLife: [{ time: "8:30 AM", activity: "Review biopsies and referral notes" }, { time: "9:00 AM", activity: "Outpatient clinic with rash, acne, and chronic disease follow-up" }, { time: "1:00 PM", activity: "Procedures or lesion reviews" }, { time: "3:30 PM", activity: "Teaching and dermoscopy review" }, { time: "5:00 PM", activity: "Plan treatment follow-up" }],
    pros: ["Strong lifestyle control", "Visual diagnostics", "Blend of medicine and procedures"],
    cons: ["Highly competitive", "Limited training spots", "Can be concentrated in urban practice"],
    futureTrends: ["Teledermatology", "Dermoscopy uptake", "Rising cosmetic dermatology interest"]
  }),
  create({
    name: "Cardiology",
    category: "medical",
    description: "A high-acuity internal medicine subspecialty for those drawn to physiology, diagnostics, and long-term disease management.",
    traitProfile: { patientInteraction: 74, proceduralInterest: 54, diagnosticReasoning: 92, fastPacedPreference: 68, workLifePriority: 40, emotionalResilience: 80, teamCollaboration: 72, precisionOrientation: 84, longTermRelationships: 66, researchCuriosity: 82, leadershipPreference: 66, trainingTolerance: 90, emergencyComfort: 70, communicationEmpathy: 72, predictableSchedulePreference: 36 },
    requiredTraits: ["High cognitive stamina", "Interest in physiology", "Long training tolerance"],
    workEnvironment: "Cardiac clinics, wards, cath-lab environments, ICU/CCU settings.",
    lifestyleRating: 2,
    competitiveness: 5,
    burnoutRisk: 4,
    salaryRangeGhs: [12000, 45000],
    salaryDisclaimer: "Broad estimate only; subspecialty, institution, and procedural mix affect earnings heavily.",
    trainingLength: "Long pathway including internal medicine then cardiology subspecialization.",
    emergencyIntensity: 4,
    patientInteractionLevel: 4,
    procedureIntensity: 3,
    ghanaOpportunities: ["Growing cardiovascular disease burden increases relevance", "Tertiary and private specialist demand continues to rise"],
    ghanaResidencyPathway: "Usually follows internal medicine training with later cardiology-focused fellowship or specialist progression.",
    relatedSpecialties: ["Internal Medicine", "Radiology", "Emergency Medicine"],
    dayInLife: [{ time: "6:45 AM", activity: "Review CCU patients and ECGs" }, { time: "8:00 AM", activity: "Ward rounds and echo planning" }, { time: "11:00 AM", activity: "Clinic for hypertension, HF, chest pain" }, { time: "2:00 PM", activity: "Procedures or imaging review" }, { time: "6:00 PM", activity: "Acute cardiac consults" }],
    pros: ["Advanced physiology", "Major disease impact", "Strong subspecialty growth"],
    cons: ["Long training", "High acuity stress", "Technology/resource constraints can limit care"],
    futureTrends: ["Preventive cardiology", "Cardiac imaging expansion", "Cath-lab capacity growth"]
  }),
  create({
    name: "Public Health / Community Medicine",
    category: "medical",
    description: "A systems-oriented field for people motivated by prevention, policy, population health, and community impact.",
    traitProfile: { patientInteraction: 48, proceduralInterest: 8, diagnosticReasoning: 62, fastPacedPreference: 40, workLifePriority: 78, emotionalResilience: 62, teamCollaboration: 84, precisionOrientation: 58, longTermRelationships: 56, researchCuriosity: 86, leadershipPreference: 82, trainingTolerance: 54, emergencyComfort: 20, communicationEmpathy: 74, predictableSchedulePreference: 82 },
    requiredTraits: ["Systems thinking", "Leadership", "Population-level curiosity"],
    workEnvironment: "Policy units, district health services, academic departments, NGOs, community programs.",
    lifestyleRating: 4,
    competitiveness: 2,
    burnoutRisk: 2,
    salaryRangeGhs: [8000, 26000],
    salaryDisclaimer: "Highly role-dependent; public service, academia, NGOs, and consulting vary widely.",
    trainingLength: "Variable; can involve residency, MPH, or other postgraduate public health routes.",
    emergencyIntensity: 1,
    patientInteractionLevel: 2,
    procedureIntensity: 1,
    ghanaOpportunities: ["Strong relevance for disease prevention, maternal-child health, and health systems strengthening", "Valuable in government, NGOs, and academia"],
    ghanaResidencyPathway: "Can include community medicine residency or public health postgraduate training linked to universities and service agencies.",
    relatedSpecialties: ["Family Medicine", "Psychiatry", "Pediatrics"],
    dayInLife: [{ time: "8:00 AM", activity: "Data review and district health planning" }, { time: "10:00 AM", activity: "Stakeholder meeting or field supervision" }, { time: "1:00 PM", activity: "Program evaluation work" }, { time: "3:00 PM", activity: "Training session or policy drafting" }, { time: "5:00 PM", activity: "Report synthesis" }],
    pros: ["Large-scale impact", "Leadership opportunities", "Good work-life structure"],
    cons: ["Less direct clinical care", "Policy progress can be slow", "May feel less hands-on"],
    futureTrends: ["Digital public health analytics", "Climate-health planning", "Community-based chronic disease prevention"]
  }),
  create({
    name: "Pathology",
    category: "medical",
    description: "A laboratory and diagnostic specialty for detail-oriented thinkers who enjoy disease mechanisms and behind-the-scenes impact.",
    traitProfile: { patientInteraction: 10, proceduralInterest: 18, diagnosticReasoning: 88, fastPacedPreference: 34, workLifePriority: 78, emotionalResilience: 56, teamCollaboration: 54, precisionOrientation: 96, longTermRelationships: 4, researchCuriosity: 82, leadershipPreference: 42, trainingTolerance: 64, emergencyComfort: 10, communicationEmpathy: 24, predictableSchedulePreference: 84 },
    requiredTraits: ["Microscopic detail", "Scientific curiosity", "Comfort without frequent patient contact"],
    workEnvironment: "Laboratories, histopathology suites, academic departments, multidisciplinary diagnostic meetings.",
    lifestyleRating: 4,
    competitiveness: 3,
    burnoutRisk: 2,
    salaryRangeGhs: [8500, 28000],
    salaryDisclaimer: "Ranges vary based on public role, private lab work, and subspecialty expertise.",
    trainingLength: "Usually 4-6 years depending on discipline and level.",
    emergencyIntensity: 1,
    patientInteractionLevel: 1,
    procedureIntensity: 1,
    ghanaOpportunities: ["Critical for cancer diagnosis, surgical support, and laboratory strengthening", "Workforce shortages can create strong impact opportunities"],
    ghanaResidencyPathway: "Training centers on lab diagnostics, autopsy, histopathology, cytology, and academic teaching where available.",
    relatedSpecialties: ["Radiology", "Dermatology", "Internal Medicine"],
    dayInLife: [{ time: "8:00 AM", activity: "Review slides and gross specimens" }, { time: "10:30 AM", activity: "Report sign-out" }, { time: "1:00 PM", activity: "Tumor board or clinician discussion" }, { time: "3:00 PM", activity: "Lab quality review or teaching" }, { time: "5:00 PM", activity: "Finalize pending cases" }],
    pros: ["Strong scientific core", "Predictable schedule", "High diagnostic importance"],
    cons: ["Very limited patient contact", "Can feel isolated from bedside care", "Equipment constraints matter"],
    futureTrends: ["Digital pathology", "Molecular diagnostics", "Oncology service integration"]
  }),
  create({
    name: "General Dentistry",
    category: "dental",
    description: "A broad dental career blending procedures, preventive care, aesthetics, and recurring patient relationships.",
    traitProfile: { patientInteraction: 84, proceduralInterest: 82, diagnosticReasoning: 66, fastPacedPreference: 56, workLifePriority: 78, emotionalResilience: 66, teamCollaboration: 68, precisionOrientation: 88, longTermRelationships: 82, researchCuriosity: 48, leadershipPreference: 60, trainingTolerance: 54, emergencyComfort: 28, communicationEmpathy: 84, predictableSchedulePreference: 82 },
    requiredTraits: ["Manual precision", "Patient communication", "Preventive mindset"],
    workEnvironment: "Dental clinics, oral health centers, private practices, school/community outreach.",
    lifestyleRating: 4,
    competitiveness: 3,
    burnoutRisk: 3,
    salaryRangeGhs: [7000, 26000],
    salaryDisclaimer: "Indicative only; private ownership and case volume materially influence income.",
    trainingLength: "Professional dental training plus optional postgraduate progression.",
    emergencyIntensity: 1,
    patientInteractionLevel: 5,
    procedureIntensity: 4,
    ghanaOpportunities: ["Good fit for public clinics and growing private urban dental demand", "Oral health education remains important nationally"],
    ghanaResidencyPathway: "Can move directly into practice after dental qualification or pursue specialty training where available.",
    relatedSpecialties: ["Orthodontics", "Pediatric Dentistry", "Periodontics"],
    dayInLife: [{ time: "8:00 AM", activity: "Preventive and restorative morning list" }, { time: "11:00 AM", activity: "Dental exams and treatment planning" }, { time: "1:00 PM", activity: "Simple procedures and follow-up care" }, { time: "3:00 PM", activity: "Counseling on oral hygiene and aesthetics" }, { time: "5:00 PM", activity: "Practice administration" }],
    pros: ["Hands-on work", "Good schedule control", "Direct visible outcomes"],
    cons: ["Fine motor strain", "Business pressures in private practice", "Can be repetitive"],
    futureTrends: ["Digital dentistry", "Preventive oral health campaigns", "Aesthetic service growth"]
  }),
  create({
    name: "Orthodontics",
    category: "dental",
    description: "A precision-focused dental specialty centered on alignment, treatment planning, and long-term aesthetic-functional care.",
    traitProfile: { patientInteraction: 76, proceduralInterest: 62, diagnosticReasoning: 78, fastPacedPreference: 38, workLifePriority: 84, emotionalResilience: 58, teamCollaboration: 56, precisionOrientation: 94, longTermRelationships: 86, researchCuriosity: 58, leadershipPreference: 48, trainingTolerance: 74, emergencyComfort: 10, communicationEmpathy: 78, predictableSchedulePreference: 90 },
    requiredTraits: ["Patience", "Detail orientation", "Interest in long treatment arcs"],
    workEnvironment: "Specialty dental clinics and referral practices.",
    lifestyleRating: 5,
    competitiveness: 4,
    burnoutRisk: 2,
    salaryRangeGhs: [10000, 32000],
    salaryDisclaimer: "Approximate only and often shaped by private specialty practice.",
    trainingLength: "Requires postgraduate specialty training after dental qualification.",
    emergencyIntensity: 1,
    patientInteractionLevel: 4,
    procedureIntensity: 3,
    ghanaOpportunities: ["Urban specialist demand is rising with aesthetic awareness", "Service access is still limited outside major centers"],
    ghanaResidencyPathway: "Postgraduate training follows dental school and may involve regional or international specialist routes depending on availability.",
    relatedSpecialties: ["General Dentistry", "Pediatric Dentistry", "Oral & Maxillofacial Surgery"],
    dayInLife: [{ time: "8:30 AM", activity: "Review treatment plans and imaging" }, { time: "9:00 AM", activity: "Appliance adjustments and new consultations" }, { time: "1:00 PM", activity: "Multidisciplinary planning for complex cases" }, { time: "3:30 PM", activity: "Retention follow-ups and counseling" }, { time: "5:00 PM", activity: "Documentation and case photography review" }],
    pros: ["High precision", "Long-term patient transformation", "Strong lifestyle"],
    cons: ["Long case timelines", "Requires specialty training", "Urban concentration of opportunities"],
    futureTrends: ["Digital aligner workflows", "3D treatment planning", "Cross-specialty aesthetic collaboration"]
  }),
  create({
    name: "Oral & Maxillofacial Surgery",
    category: "dental",
    description: "A surgical dental specialty for those who want complex procedures, trauma care, and facial reconstruction exposure.",
    traitProfile: { patientInteraction: 54, proceduralInterest: 96, diagnosticReasoning: 76, fastPacedPreference: 80, workLifePriority: 28, emotionalResilience: 86, teamCollaboration: 78, precisionOrientation: 92, longTermRelationships: 26, researchCuriosity: 56, leadershipPreference: 78, trainingTolerance: 92, emergencyComfort: 88, communicationEmpathy: 54, predictableSchedulePreference: 20 },
    requiredTraits: ["Surgical drive", "Stress tolerance", "Excellent hand skills"],
    workEnvironment: "Operating theatres, trauma services, maxillofacial clinics, dental surgery units.",
    lifestyleRating: 2,
    competitiveness: 5,
    burnoutRisk: 4,
    salaryRangeGhs: [11000, 42000],
    salaryDisclaimer: "Indicative only; operative work and private referrals create wide variation.",
    trainingLength: "Long specialty pathway after dentistry, often with highly competitive training.",
    emergencyIntensity: 5,
    patientInteractionLevel: 3,
    procedureIntensity: 5,
    ghanaOpportunities: ["Strong relevance for facial trauma, tumors, and complex extractions", "High-value role in tertiary hospitals"],
    ghanaResidencyPathway: "Typically requires structured postgraduate surgical dental training through accredited institutions or regional pathways.",
    relatedSpecialties: ["General Surgery", "Orthopedic Surgery", "Orthodontics"],
    dayInLife: [{ time: "6:30 AM", activity: "Review facial trauma admissions" }, { time: "8:00 AM", activity: "Ward round and operative briefing" }, { time: "9:30 AM", activity: "Major surgery list" }, { time: "2:30 PM", activity: "Specialist clinic and post-op checks" }, { time: "7:00 PM", activity: "Emergency call for trauma or airway cases" }],
    pros: ["Complex surgery", "Major functional impact", "Respected tertiary role"],
    cons: ["Very demanding training", "High emergency burden", "Burnout risk"],
    futureTrends: ["Reconstructive techniques", "Trauma systems development", "Digital surgical planning"]
  }),
  create({
    name: "Pediatric Dentistry",
    category: "dental",
    description: "A child-centered dental specialty combining prevention, behavior guidance, and family communication.",
    traitProfile: { patientInteraction: 92, proceduralInterest: 62, diagnosticReasoning: 62, fastPacedPreference: 54, workLifePriority: 74, emotionalResilience: 74, teamCollaboration: 68, precisionOrientation: 78, longTermRelationships: 88, researchCuriosity: 46, leadershipPreference: 50, trainingTolerance: 62, emergencyComfort: 20, communicationEmpathy: 94, predictableSchedulePreference: 74 },
    requiredTraits: ["Patience with children", "Family communication", "Preventive care focus"],
    workEnvironment: "Pediatric dental clinics, hospitals, community oral health services.",
    lifestyleRating: 4,
    competitiveness: 3,
    burnoutRisk: 3,
    salaryRangeGhs: [8000, 28000],
    salaryDisclaimer: "Approximate only; clinic setting and case volume influence income.",
    trainingLength: "Requires postgraduate specialty training after dentistry.",
    emergencyIntensity: 1,
    patientInteractionLevel: 5,
    procedureIntensity: 3,
    ghanaOpportunities: ["Strong preventive oral health relevance", "Potential impact through school and family-focused services"],
    ghanaResidencyPathway: "Often follows dental qualification with specialty training in child oral health and behavior management.",
    relatedSpecialties: ["General Dentistry", "Pediatrics", "Orthodontics"],
    dayInLife: [{ time: "8:00 AM", activity: "Morning clinic for exams and preventive care" }, { time: "10:30 AM", activity: "Behavior-guided restorative sessions" }, { time: "1:00 PM", activity: "Parent counseling and oral hygiene education" }, { time: "3:00 PM", activity: "Follow-up cases and school oral health planning" }, { time: "5:00 PM", activity: "Documentation and care coordination" }],
    pros: ["Meaningful child-focused relationships", "Strong communication role", "Preventive impact"],
    cons: ["Behavior management can be taxing", "Requires patience", "Specialty training needed"],
    futureTrends: ["Sedation service growth", "School oral health programs", "Preventive fluoride and sealant expansion"]
  }),
  create({
    name: "Periodontics",
    category: "dental",
    description: "A gum and supporting-structure specialty balancing precision procedures, chronic disease management, and oral-systemic health.",
    traitProfile: { patientInteraction: 70, proceduralInterest: 74, diagnosticReasoning: 68, fastPacedPreference: 46, workLifePriority: 78, emotionalResilience: 62, teamCollaboration: 60, precisionOrientation: 92, longTermRelationships: 72, researchCuriosity: 56, leadershipPreference: 48, trainingTolerance: 66, emergencyComfort: 14, communicationEmpathy: 74, predictableSchedulePreference: 82 },
    requiredTraits: ["Fine motor skill", "Chronic care mindset", "Detail orientation"],
    workEnvironment: "Dental specialty clinics, referral centers, periodontal surgery suites.",
    lifestyleRating: 4,
    competitiveness: 3,
    burnoutRisk: 2,
    salaryRangeGhs: [9000, 30000],
    salaryDisclaimer: "Estimated only; private referral practice and implant-related services can widen the range.",
    trainingLength: "Postgraduate specialty training after dental qualification.",
    emergencyIntensity: 1,
    patientInteractionLevel: 4,
    procedureIntensity: 4,
    ghanaOpportunities: ["Growing need as oral-systemic health awareness improves", "Useful in both specialist referral and multidisciplinary dental care"],
    ghanaResidencyPathway: "Typically follows dental school through specialist postgraduate training in periodontal medicine and surgery.",
    relatedSpecialties: ["General Dentistry", "Orthodontics", "Oral & Maxillofacial Surgery"],
    dayInLife: [{ time: "8:30 AM", activity: "Review referrals and radiographs" }, { time: "9:00 AM", activity: "Periodontal surgery or scaling sessions" }, { time: "1:00 PM", activity: "Maintenance follow-up and education" }, { time: "3:00 PM", activity: "Interdisciplinary planning with prosthodontic/ortho colleagues" }, { time: "5:00 PM", activity: "Case documentation" }],
    pros: ["Precision procedures", "Chronic relationship-based care", "Predictable schedule"],
    cons: ["Narrower public awareness", "Specialty training needed", "Can be repetitive for some people"],
    futureTrends: ["Implant maintenance growth", "Laser and digital planning tools", "Greater oral-systemic health integration"]
  })
];

export const specialtiesById = Object.fromEntries(specialties.map((item) => [item.id, item]));
